#pragma once

#include <array>
#include <cstddef>
#include <cstdint>
#include <filesystem>
#include <memory>
#include <mutex>
#include <optional>
#include <span>
#include <string>
#include <vector>
#include "utils/Json.hpp"
#include <opencv2/core.hpp>

#include "vc/core/types/Sampling.hpp"
#include "vc/core/types/SampleParams.hpp"
#include "vc/core/types/Array3D.hpp"
#include "vc/core/render/ChunkCache.hpp"
#include "vc/core/util/RemoteAuth.hpp"

namespace vc::render { class IChunkedArray; }

struct CompositeParams;

class Volume
{
public:
    // Static flag to skip zarr shape validation against meta.json
    static inline thread_local bool skipShapeCheck = false;

    Volume() = delete;

    explicit Volume(std::filesystem::path path);
    struct RemoteConstructTag {};
    Volume(std::filesystem::path path, RemoteConstructTag);

    ~Volume() noexcept;


    static std::shared_ptr<Volume> New(std::filesystem::path path);

    struct PyramidPolicy {
        enum class Reduction {
            Mean,
            Max,
            BinaryOr,
        };

        Reduction reduction = Reduction::Mean;
    };

    // Create a Volume backed by a remote zarr store over HTTP.
    // If auth is provided, it is used as-is; otherwise credentials are read
    // from environment variables. cacheRoot is currently ignored.
    static std::shared_ptr<Volume> NewFromUrl(
        const std::string& url,
        const std::filesystem::path& cacheRoot = {},
        const vc::HttpAuth& auth = {});

    [[nodiscard]] bool isRemote() const noexcept { return isRemote_; }
    [[nodiscard]] std::string id() const;
    [[nodiscard]] std::string name() const;
    [[nodiscard]] const utils::Json& metadata() const noexcept { return metadata_; }
    [[nodiscard]] utils::Json rootAttributes() const;
    [[nodiscard]] const std::string& remoteUrl() const noexcept { return remoteUrl_; }
    [[nodiscard]] const vc::HttpAuth& remoteAuth() const noexcept { return remoteAuth_; }
    [[nodiscard]] std::filesystem::path path() const noexcept { return path_; }

    [[nodiscard]] int sliceWidth() const noexcept;
    [[nodiscard]] int sliceHeight() const noexcept;
    [[nodiscard]] int numSlices() const noexcept;
    // Zarr/storage order: [z, y, x] = [slices, height, width].
    [[nodiscard]] std::array<int, 3> shape() const noexcept;
    [[nodiscard]] std::array<int, 3> shape(int level) const;
    // Coordinate/UI order: [x, y, z] = [width, height, slices].
    [[nodiscard]] std::array<int, 3> shapeXyz() const noexcept;
    [[nodiscard]] double voxelSize() const;
    [[nodiscard]] double fillValue() const noexcept { return zarrFillValue_; }

    [[nodiscard]] size_t numScales() const noexcept;
    [[nodiscard]] int baseScaleLevel() const noexcept { return 0; }
    [[nodiscard]] bool hasScaleLevel(int level) const noexcept;
    [[nodiscard]] int finestPresentScaleLevelAtOrBelow(int level) const;
    [[nodiscard]] PyramidPolicy::Reduction pyramidReduction() const noexcept
    {
        return pyramidReduction_;
    }

    enum class MissingScaleLevelPolicy {
        Error,
        AllFill,
        Empty,
        VirtualDownsample,
    };

    // --- Cache management ---

    [[nodiscard]] vc::render::IChunkedArray* chunkedCache();
    [[nodiscard]] std::shared_ptr<vc::render::ChunkCache> createChunkCache(
        vc::render::ChunkCache::Options options) const;

    // Set cache budget for the chunked sampling cache.
    void setCacheBudget(size_t hotBytes);

    // --- Sampling API ---

    // Single-slice blocking sample (uint8)
    void sample(cv::Mat_<uint8_t>& out,
                const cv::Mat_<cv::Vec3f>& coords,
                const vc::SampleParams& params);

    // Blocking integer reads through the chunked local/remote cache.
    // ZYX order matches zarr storage and numpy-style volume indexing:
    //   offset = [z, y, x], shape = [z, y, x].
    bool readZYX(Array3D<uint8_t>& out,
                 const std::array<int, 3>& offsetZYX,
                 int level = 0,
                 MissingScaleLevelPolicy missingPolicy = MissingScaleLevelPolicy::Error);
    static void readZYX(Array3D<uint8_t>& out,
                        const std::array<int, 3>& offsetZYX,
                        vc::render::IChunkedArray& array,
                        int level = 0);

protected:
    std::filesystem::path path_;
    utils::Json metadata_;
    bool metadataAutoGenerated_{false};

    int _width{0};
    int _height{0};
    int _slices{0};

    std::vector<std::array<int, 3>> zarrLevelShapes_;
    std::vector<std::array<int, 3>> zarrLevelChunkShapes_;
    vc::render::ChunkDtype zarrDtype_ = vc::render::ChunkDtype::UInt8;
    double zarrFillValue_ = 0.0;
    PyramidPolicy::Reduction pyramidReduction_ = PyramidPolicy::Reduction::Mean;
    void zarrOpen();

    // Cache ownership
    mutable std::shared_ptr<vc::render::ChunkCache> chunkedCache_;
    mutable std::mutex cacheMutex_;
    size_t cacheBudgetHot_ = 8ULL << 30;   // 8 GB default
    int ioThreads_ = 0;  // 0 = use default

    void loadMetadata();

    // Remote volume state
    bool isRemote_ = false;
    std::string remoteUrl_;
    vc::HttpAuth remoteAuth_;
    size_t remoteNumScales_ = 0;
};
