# LeJEPA 2D pretraining configuration with Primus-M encoder
# Uses rotated 2D plane slices from 3D volumes
# Uses SIGReg (Sketched Isotropic Gaussian Regularization) for unsupervised learning

# Placeholder target for compatibility with base trainer
# (LeJEPA is self-supervised and doesn't use traditional targets)
targets:
  lejepa:
    activation: none
    weight: 1.0

tr_config:
  patch_size: [768, 768]  # H, W - 2D patch size (triggers 2D mode)
  initial_lr: 1e-3
  weight_decay: 0.05
  max_epoch: 1000

model_config:
  architecture_type: "primus_l"
  patch_embed_size: [8, 8]  # Patch size for 2D ViT embedding
  drop_path_rate: 0.1
  proj_drop_rate: 0.0
  attn_drop_rate: 0.0
  patch_drop_rate: 0.0  # No masking for LeJEPA

# LeJEPA-specific parameters
lejepa_config:
  lambda: 0.2  # Balance between invariance and SIGReg loss
  num_global_views: 2  # Views with lighter augmentation (full resolution)
  num_local_views: 6  # Views with stronger augmentation (cropped + resized)
  sigreg_num_slices: 512  # Random projection directions for SIGReg
  proj_dim: 256  # Projection dimension (128-512 range recommended)
  # Crop scale ranges (area-based for 2D: scale=0.3 means 30% of area)
  global_crop_scale: [0.3, 1.0]   # Large crops: 30-100% of area
  local_crop_scale: [0.05, 0.3]  # Small crops: 5-30% of area
  primus_variant: "L"  # S, B, M, or L

dataset_config:
  # Rotated plane extraction parameters
  plane_rotation_max_degrees: 45  # Max in-plane rotation (yaw)
  plane_tilt_max_degrees: 45  # Max out-of-plane tilt
  min_labeled_ratio: 0          # No minimum labeled voxel ratio
  min_bbox_percent: 0           # No bounding box coverage requirement
  skip_patch_validation: false  # Validate patches (now works with image-only)
  allow_unlabeled_data: true    # Accept volumes without labels
  normalization_scheme: "zscore"  # z-score normalization per volume
  ome_zarr_resolution: 1

  slice_sample_planes: ["x", "y", "z"]
  slice_plane_weights: {x: 1.0, y: 1.0, z: 1.0}

  # Filter out blank/empty patches using image intensity
  unlabeled_foreground_enabled: true
  unlabeled_foreground_threshold: 0.5      # Min 50% non-zero voxels
  unlabeled_foreground_bbox_threshold: 1   # Min 100% bbox coverage (stricter for 2D)
  valid_patch_find_resolution: 2           # Use zarr level 3 for faster validation
