tr_setup:
  model_name: sheet_normals_ink
  autoconfigure: true
  load_weights_only: false
tr_config:
  patch_size:
  - 128
  - 128
  - 128
  initial_lr: 1e-2
model_config:
  final_config:
    model_name: sheet_normals_ink
    use_timm_encoder: false
    basic_encoder_block: BasicBlockD
    basic_decoder_block: BasicBlockD
    bottleneck_block: BasicBlockD
    features_per_stage:
    - 32
    - 64
    - 128
    - 256
    - 512
    - 512
    num_stages: 6
    n_blocks_per_stage:
    - 1
    - 3
    - 4
    - 6
    - 6
    - 6
    n_conv_per_stage_decoder:
    - 1
    - 1
    - 1
    - 1
    - 1
    kernel_sizes:
    - - 3
      - 3
      - 3
    - - 3
      - 3
      - 3
    - - 3
      - 3
      - 3
    - - 3
      - 3
      - 3
    - - 3
      - 3
      - 3
    - - 3
      - 3
      - 3
    pool_op: AvgPool3d
    pool_op_kernel_sizes: &id001
    - - 1
      - 1
      - 1
    - - 2
      - 2
      - 2
    - - 2
      - 2
      - 2
    - - 2
      - 2
      - 2
    - - 2
      - 2
      - 2
    - - 2
      - 2
      - 2
    conv_op: Conv3d
    conv_bias: false
    norm_op: InstanceNorm3d
    norm_op_kwargs:
      affine: false
      eps: 1.0e-05
    dropout_op: Dropout3d
    dropout_op_kwargs:
      p: 0.0
    nonlin: LeakyReLU
    nonlin_kwargs:
      negative_slope: 0.01
      inplace: true
    strides: *id001
    return_skips: true
    do_stem: true
    stem_channels: null
    bottleneck_channels: null
    stochastic_depth_p: 0.0
    squeeze_excitation: false
    squeeze_excitation_reduction_ratio: null
    op_dims: 3
    patch_size:
    - 128
    - 128
    - 128
    batch_size: 2
    in_channels: 1
    vram_target: 16.0
    autoconfigure: true
    targets: &id002
      sheet:
        out_channels: 1
        activation: none
        weight: 1
        loss_fn: BCEDiceLoss
        volumes:
        - data_volume: /mnt/raid_nvme/scroll_volumes/s1.zarr
          label_volume: /mnt/raid_nvme/labels/surfaces/s1_surface_label.zarr/0.zarr
          format: zarr_local
      normals:
        out_channels: 3
        activation: none
        weight: 0.75
        loss_fn: MaskedCosineLoss
        volumes:
        - data_volume: /mnt/raid_nvme/scroll_volumes/s1.zarr
          label_volume: /mnt/raid_nvme/labels/normals/s1_normals.zarr
          format: zarr_local
      ink:
        out_channels: 1
        activation: none
        weight: 1
        loss_fn: BCEDiceLoss
        volumes:
        - data_volume: /mnt/raid_nvme/scroll_volumes/s1.zarr
          label_volume: /mnt/raid_nvme/labels/s1_ink.zarr
          format: zarr_local
dataset_config:
  min_labeled_ratio: 0.08
  min_bbox_percent: 0.98
  targets: *id002
inference_config: {}
